POST http://localhost:3500/register
Content-Type: application/json

{
    "username": "brahimtnc@gmail.com1",
    "pwd": "sadas"
}

###

POST  http://localhost:3500/login
Content-Type: application/json

{
    "username": "brahimtnc@gmail.com1",
    "pwd": "sadas"
}

###

POST  http://localhost:3500/refresh
Content-Type: application/json

{
    
}



###

GET  http://localhost:3500/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJyYWhpbXRuY0BnbWFpbC5jb20xIiwiaWF0IjoxNjU1NjQ5NDk2LCJleHAiOjE2NTU2NDk1MjZ9.NjeXZ50mW1ZPaqOD54WigvzYKJI9hyJ8zyOzh2uFt-U  